/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ThreadJni */

#ifndef _Included_ThreadJni
#define _Included_ThreadJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ThreadJni
 * Method:    CreateThread
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ThreadJni_CreateThread
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
